title: Kaveri Pradeep
logo: /assets/img/photo.png
description: Kaveri is a data science professional with 9 years of experience.She is working as Manager Analytics with Axtria. Prior to this she has worked with organizations such as BCG & UHG.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
