title: Kaveri Pradeep
logo: /assets/img/photo.jpg
description: 
  <p align="center">
  <a href="www.linkedin.com/in/kaveri-pradeep-ab8201b8/">LinkedIn</a>
  <br>
  Kaveri is a data science professional with 9 years of experience.She is working as Manager Analytics with Axtria. Prior to this she has worked with organizations such as BCG & UHG.
  <br>
  </p>
theme: jekyll-theme-minimal
